/* Generated by Together */
/*
	Class OuterServer��������GateServer�����ӹ�����ͨ��
	ע�⣺OuterServer������һ��Struct�Ľṹ��ȫ���Ե�������������GameServerApp�࣬��Ҫ�����������
*/
#ifndef OUTERSERVER_H
#define OUTERSERVER_H
#include "ThreadPool.h"
#include "CommRPC.h"
#include "PacketQueue.h"
#include "NetCommand.h"
#include "GameApp.h"

_DBC_USING

class OuterServer : public TcpServerApp, public RPCMGR, public PKQueue
{
	friend class	ToGateServer;

public:
	OuterServer(ThreadPool *proc,ThreadPool *comm);
	~OuterServer();

private:
	void	ProcessData(DataSocket *datasock,RPacket recvbuf);
	WPacket	ServeCall(DataSocket *datasock,RPacket in_para);

	bool	OnConnect(DataSocket *datasock);				//����ֵ:true-��������,false-����������
	void	OnDisconnect(DataSocket *datasock,int reason);	//reasonֵ:0-���س��������˳���-3-���类�Է��رգ�-1-Socket����;-5-�����ȳ������ơ�
	void	OnProcessData(DataSocket *datasock,RPacket recvbuf);
	WPacket	OnServeCall(DataSocket *datasock,RPacket in_para)
	{
		if (in_para.ReadCmd() == CMD_TM_PING)
			return in_para;
		else return SyncPK(datasock,in_para);
	}

	long			m_count;		//���ü�����
	std::recursive_mutex			m_mutdisc;
};


class ToGateServer : public Task
{
public:
    ToGateServer() {dwTimeOut = 3000;}

private:
    virtual long Process();
    DWORD	dwTimeOut;
};

//extern OuterServer * g_gmout;
extern char	g_szConnectLog[256];




#endif //OUTERSERVER_H
